// packages/web/src/modules/categories/CategoryForm.vue
<script setup lang="ts">
import { Button } from '@/shared/components/ui/button'
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/shared/components/ui/form'
import { Input } from '@/shared/components/ui/input'
import { Switch } from '@/shared/components/ui/switch'
import { Textarea } from '@/shared/components/ui/textarea'
import { POSTCategorySchema } from '@fresclean/api/schema'
import { useForm, type FormOptions } from 'vee-validate'
import type z from 'zod'

type ServiceForm = z.input<typeof POSTCategorySchema>
type ServiceFormProps = FormOptions<ServiceForm>
const props = defineProps<ServiceFormProps>()
const emit = defineEmits<{
  submit: [data: z.infer<typeof POSTCategorySchema>]
}>()

const { handleSubmit, isSubmitting } = useForm({
  ...props,
  validationSchema: POSTCategorySchema,
})

const onSubmit = handleSubmit((data) => emit('submit', data))
</script>

<template>
  <form @submit="onSubmit" class="flex flex-col gap-y-3">
    <FormField v-slot="{ componentField }" name="name">
      <FormItem>
        <FormLabel asterisk> Name </FormLabel>
        <FormControl>
          <Input placeholder="Category Name" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ componentField }" name="description">
      <FormItem>
        <FormLabel> Description </FormLabel>
        <FormControl>
          <Textarea placeholder="Category Description" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ value, handleChange }" name="is_active">
      <FormItem class="flex flex-row items-center justify-between rounded-lg border p-4">
        <div class="space-y-0.5">
          <FormLabel class="text-base"> Activation Status </FormLabel>
        </div>
        <FormControl>
          <Switch :model-value="value" @update:model-value="handleChange" />
        </FormControl>
      </FormItem>
    </FormField>

    <Button :loading="isSubmitting" size="lg" type="submit" class="w-full mt-3"> Submit </Button>
  </form>
</template>

// packages/web/src/features/categories/components/category-form.tsx
import { POSTCategorySchema } from "@fresclean/api/schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { PlusIcon } from "@phosphor-icons/react";
import { Controller, useForm } from "react-hook-form";
import type { z } from "zod";
import { Button } from "@/components/ui/button";
import {
	Field,
	FieldContent,
	FieldDescription,
	FieldError,
	FieldGroup,
	FieldLabel,
	FieldTitle,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";

export type CategoryFormState = z.infer<typeof POSTCategorySchema>;

const defaultForm: CategoryFormState = {
	name: "",
	description: "",
	is_active: true,
};

type CategoryFormProps = {
	defaultValues?: CategoryFormState;
	handleOnSubmit: (values: CategoryFormState) => Promise<void> | void;
	isEditing: boolean;
	onReset: () => void;
};

export function CategoryForm({
	defaultValues,
	handleOnSubmit,
	isEditing,
	onReset,
}: CategoryFormProps) {
	const form = useForm({
		resolver: zodResolver(POSTCategorySchema),
		defaultValues: defaultValues ?? defaultForm,
	});
	const isSubmitting = form.formState.isSubmitting;

	return (
		<form onSubmit={form.handleSubmit(handleOnSubmit)}>
			<FieldGroup>
				<Controller
					name="name"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="category-name" asterisk>
								Name
							</FieldLabel>
							<Input
								{...field}
								id="category-name"
								placeholder="e.g. Laundry"
								aria-invalid={fieldState.invalid}
								disabled={isSubmitting}
								className="h-10"
							/>
							{fieldState.invalid && <FieldError errors={[fieldState.error]} />}
						</Field>
					)}
				/>

				<Controller
					name="description"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid} className="md:col-span-2">
							<FieldLabel htmlFor="category-description">
								Description
							</FieldLabel>
							<Input
								{...field}
								id="category-description"
								placeholder="e.g. Core laundry services"
								aria-invalid={fieldState.invalid}
								value={field.value ?? ""}
								disabled={isSubmitting}
								className="h-10"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="is_active"
					control={form.control}
					render={({ field }) => (
						<FieldLabel htmlFor="category-active">
							<Field orientation="horizontal">
								<FieldContent>
									<FieldTitle>Category Status</FieldTitle>
									<FieldDescription>
										Active category will be shown in the app.
									</FieldDescription>
								</FieldContent>
								<Switch
									id="category-active"
									checked={field.value}
									onCheckedChange={(checked) => field.onChange(!!checked)}
									disabled={isSubmitting}
								/>
							</Field>
						</FieldLabel>
					)}
				/>

				<div className="flex flex-wrap gap-2 md:col-span-2 md:justify-end">
					{isEditing ? (
						<Button
							type="button"
							variant="outline"
							onClick={onReset}
							disabled={isSubmitting}
						>
							Cancel edit
						</Button>
					) : null}
					<Button
						type="submit"
						loading={isSubmitting}
						icon={<PlusIcon className="size-4" />}
					>
						{isEditing ? "Update Category" : "Create Category"}
					</Button>
				</div>
			</FieldGroup>
		</form>
	);
}
