// packages/web/src/features/products/components/product-form.tsx
import { POSTProductSchema } from "@fresclean/api/schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { PlusIcon } from "@phosphor-icons/react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";
import { CurrencyInput } from "@/components/form/currency-input";
import { Button } from "@/components/ui/button";
import {
	Field,
	FieldError,
	FieldGroup,
	FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { CategoryAutocomplete } from "@/features/orders/components/category-autocomplete";

const productFormResolverSchema = z.object({
	...POSTProductSchema.shape,
	stock: z.preprocess((value) => Number(value), POSTProductSchema.shape.stock),
	category_id: z.preprocess(
		(value) => Number(value),
		POSTProductSchema.shape.category_id,
	),
});

export type ProductFormState = z.infer<typeof productFormResolverSchema>;

const defaultForm: ProductFormState = {
	name: "",
	description: "",
	is_active: true,
	sku: "",
	uom: "pcs",
	stock: 0,
	category_id: 0,
	cogs: "",
	price: "",
};

type ProductFormProps = {
	defaultValues?: ProductFormState;
	handleOnSubmit: (values: ProductFormState) => Promise<void> | void;
	isEditing: boolean;
	onReset: () => void;
};

export function ProductForm({
	defaultValues,
	handleOnSubmit,
	isEditing,
	onReset,
}: ProductFormProps) {
	const form = useForm({
		resolver: zodResolver(productFormResolverSchema),
		defaultValues: defaultValues ?? defaultForm,
	});
	const isSubmitting = form.formState.isSubmitting;

	return (
		<form onSubmit={form.handleSubmit(handleOnSubmit)}>
			<FieldGroup>
				<Controller
					name="name"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="product-name" asterisk>
								Name
							</FieldLabel>
							<Input
								{...field}
								id="product-name"
								placeholder="e.g. Liquid Detergent"
								aria-invalid={fieldState.invalid}
								disabled={isSubmitting}
								className="h-10"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="sku"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="product-sku" asterisk>
								SKU
							</FieldLabel>
							<Input
								{...field}
								id="product-sku"
								placeholder="e.g. PRD-001"
								aria-invalid={fieldState.invalid}
								disabled={isSubmitting}
								className="h-10"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="category_id"
					control={form.control}
					render={({ field, fieldState }) => (
						<CategoryAutocomplete
							value={field.value ? String(field.value) : ""}
							onValueChange={(value) => field.onChange(Number(value))}
							required
							disabled={isSubmitting}
							error={fieldState.error}
						/>
					)}
				/>

				<Controller
					name="uom"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="product-uom" asterisk>
								UOM
							</FieldLabel>
							<Input
								{...field}
								id="product-uom"
								placeholder="e.g. pcs"
								aria-invalid={fieldState.invalid}
								disabled={isSubmitting}
								className="h-10"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="stock"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="product-stock" asterisk>
								Stock
							</FieldLabel>
							<Input
								id="product-stock"
								type="number"
								placeholder="e.g. 100"
								aria-invalid={fieldState.invalid}
								value={String(field.value)}
								onChange={(event) => field.onChange(Number(event.target.value))}
								disabled={isSubmitting}
								className="h-10"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="description"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid} className="md:col-span-2">
							<FieldLabel htmlFor="product-description">Description</FieldLabel>
							<Input
								{...field}
								id="product-description"
								placeholder="e.g. 1L refill bottle"
								aria-invalid={fieldState.invalid}
								value={field.value ?? ""}
								disabled={isSubmitting}
								className="h-10"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="cogs"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="product-cogs" asterisk>
								COGS
							</FieldLabel>
							<CurrencyInput
								id="product-cogs"
								placeholder="Rp0"
								value={field.value}
								onValueChange={field.onChange}
								disabled={isSubmitting}
								required
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="price"
					control={form.control}
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="product-price" asterisk>
								Price
							</FieldLabel>
							<CurrencyInput
								id="product-price"
								placeholder="Rp0"
								value={field.value}
								onValueChange={field.onChange}
								disabled={isSubmitting}
								required
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					name="is_active"
					control={form.control}
					render={({ field }) => (
						<Field className="flex-row items-center justify-between md:col-span-2">
							<FieldLabel htmlFor="product-active">Active</FieldLabel>
							<Switch
								id="product-active"
								checked={field.value}
								onCheckedChange={(checked) => field.onChange(!!checked)}
								disabled={isSubmitting}
							/>
						</Field>
					)}
				/>

				<div className="flex flex-wrap gap-2 md:col-span-2 md:justify-end">
					{isEditing ? (
						<Button
							type="button"
							variant="outline"
							onClick={onReset}
							disabled={isSubmitting}
						>
							Cancel edit
						</Button>
					) : null}
					<Button
						type="submit"
						loading={isSubmitting}
						icon={<PlusIcon className="size-4" weight="duotone" />}
					>
						{isEditing ? "Update Product" : "Create Product"}
					</Button>
				</div>
			</FieldGroup>
		</form>
	);
}

// packages/web/src/modules/products/ProductForm.vue
<script setup lang="ts">
import CategoriesSelect from '@/shared/components/CategoriesSelect.vue'
import { Button } from '@/shared/components/ui/button'
import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/shared/components/ui/form'
import { Input } from '@/shared/components/ui/input'
import { Switch } from '@/shared/components/ui/switch'
import { Textarea } from '@/shared/components/ui/textarea'
import { useForm, type FormOptions } from 'vee-validate'
import type z from 'zod'
import { POSTProductSchema } from '@fresclean/api/schema'

type ServiceForm = z.input<typeof POSTProductSchema>
type ServiceFormProps = FormOptions<ServiceForm> & {
  type: 'post' | 'put'
}
const props = defineProps<ServiceFormProps>()
const emit = defineEmits<{
  submit: [data: z.infer<typeof POSTProductSchema>]
}>()

const { handleSubmit, isSubmitting } = useForm({
  ...props,
  validationSchema: POSTProductSchema,
})

const onSubmit = handleSubmit((data) => emit('submit', data))
</script>

<template>
  <form @submit="onSubmit" class="flex flex-col gap-y-3">
    <FormField v-slot="{ componentField }" name="sku">
      <FormItem>
        <FormLabel asterisk> SKU </FormLabel>
        <FormControl>
          <Input :disabled="type === 'put'" placeholder="Product SKU" v-bind="componentField" />
        </FormControl>
        <FormDescription v-if="type === 'put'"> SKU can't be edited </FormDescription>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ componentField }" name="name">
      <FormItem>
        <FormLabel asterisk> Product </FormLabel>
        <FormControl>
          <Input placeholder="Product Name" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ componentField }" name="category_id">
      <CategoriesSelect v-bind="componentField" />
    </FormField>

    <div class="grid grid-cols-2 gap-x-3">
      <FormField v-slot="{ componentField }" name="price">
        <FormItem>
          <FormLabel asterisk> Price </FormLabel>
          <FormControl>
            <Input
              v-bind="componentField"
              v-model.currency="componentField.modelValue"
              placeholder="Enter price amount"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>

      <FormField v-slot="{ componentField }" name="cogs">
        <FormItem>
          <FormLabel asterisk> COGS </FormLabel>
          <FormControl>
            <Input
              v-bind="componentField"
              v-model.currency="componentField.modelValue"
              placeholder="Enter COGS amount"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>
    </div>

    <FormField v-slot="{ componentField }" name="description">
      <FormItem>
        <FormLabel> Description </FormLabel>
        <FormControl>
          <Textarea placeholder="Product Description" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <div class="grid grid-cols-2 gap-x-3">
      <FormField v-slot="{ componentField }" name="uom">
        <FormItem>
          <FormLabel asterisk> UOM </FormLabel>
          <FormControl>
            <Input placeholder="UOM" v-bind="componentField" />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>

      <FormField v-slot="{ componentField }" name="stock">
        <FormItem>
          <FormLabel asterisk> Stock </FormLabel>
          <FormControl>
            <Input type="number" placeholder="Stock" v-bind="componentField" />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>
    </div>

    <FormField v-slot="{ value, handleChange }" name="is_active">
      <FormItem class="flex flex-row items-center justify-between rounded-lg border p-4">
        <div class="space-y-0.5">
          <FormLabel class="text-base"> Activation Status </FormLabel>
        </div>
        <FormControl>
          <Switch :model-value="value" @update:model-value="handleChange" />
        </FormControl>
      </FormItem>
    </FormField>

    <Button :loading="isSubmitting" size="lg" type="submit" class="w-full mt-3"> Submit </Button>
  </form>
</template>
