// packages/web/src/modules/services/ServiceForm.vue
<script setup lang="ts">
import CategoriesSelect from '@/shared/components/CategoriesSelect.vue'
import { Button } from '@/shared/components/ui/button'
import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/shared/components/ui/form'
import { Input } from '@/shared/components/ui/input'
import { Switch } from '@/shared/components/ui/switch'
import { Textarea } from '@/shared/components/ui/textarea'
import { POSTServiceSchema } from '@fresclean/api/schema'
import { useForm, type FormOptions } from 'vee-validate'
import type z from 'zod'

type ServiceForm = z.input<typeof POSTServiceSchema>
type ServiceFormProps = FormOptions<ServiceForm> & {
  type: 'post' | 'put'
}
const props = defineProps<ServiceFormProps>()
const emit = defineEmits<{
  submit: [data: z.infer<typeof POSTServiceSchema>]
}>()

const { handleSubmit, isSubmitting } = useForm({
  ...props,
  validationSchema: POSTServiceSchema,
})

const onSubmit = handleSubmit((data) => emit('submit', data))
</script>

<template>
  <form @submit="onSubmit" class="flex flex-col gap-y-3">
    <FormField v-slot="{ componentField }" name="code">
      <FormItem>
        <FormLabel asterisk> Code </FormLabel>
        <FormControl>
          <Input
            :disabled="type === 'put'"
            maxlength="4"
            placeholder="Service Code"
            v-bind="componentField"
          />
        </FormControl>
        <FormDescription v-if="type === 'put'"> Code can't be edited </FormDescription>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ componentField }" name="name">
      <FormItem>
        <FormLabel asterisk> Service </FormLabel>
        <FormControl>
          <Input placeholder="Service Name" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ componentField }" name="category_id">
      <CategoriesSelect v-bind="componentField" />
    </FormField>

    <div class="grid grid-cols-2 gap-x-3">
      <FormField v-slot="{ componentField }" name="price">
        <FormItem>
          <FormLabel asterisk> Price </FormLabel>
          <FormControl>
            <Input
              v-bind="componentField"
              v-model.currency="componentField.modelValue"
              placeholder="Enter price amount"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>

      <FormField v-slot="{ componentField }" name="cogs">
        <FormItem>
          <FormLabel asterisk> COGS </FormLabel>
          <FormControl>
            <Input
              v-bind="componentField"
              v-model.currency="componentField.modelValue"
              placeholder="Enter COGS amount"
            />
          </FormControl>
          <FormMessage />
        </FormItem>
      </FormField>
    </div>

    <FormField v-slot="{ componentField }" name="description">
      <FormItem>
        <FormLabel> Description </FormLabel>
        <FormControl>
          <Textarea placeholder="Description" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ value, handleChange }" name="is_active">
      <FormItem class="flex flex-row items-center justify-between rounded-lg border p-4">
        <div class="space-y-0.5">
          <FormLabel class="text-base"> Activation Status </FormLabel>
        </div>
        <FormControl>
          <Switch :model-value="value" @update:model-value="handleChange" />
        </FormControl>
      </FormItem>
    </FormField>

    <Button :loading="isSubmitting" size="lg" type="submit" class="w-full mt-3"> Submit </Button>
  </form>
</template>

// packages/web/src/features/services/components/service-form.tsx
import { POSTServiceSchema } from "@fresclean/api/schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { PlusIcon } from "@phosphor-icons/react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";
import { CurrencyInput } from "@/components/form/currency-input";
import { Button } from "@/components/ui/button";
import {
	Field,
	FieldError,
	FieldGroup,
	FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { CategoryAutocomplete } from "@/features/orders/components/category-autocomplete";

const serviceFormResolverSchema = z.object({
	...POSTServiceSchema.shape,
	category_id: z.preprocess(
		(value) => Number(value),
		POSTServiceSchema.shape.category_id,
	),
});

export type ServiceFormState = z.infer<typeof serviceFormResolverSchema>;

const defaultForm: ServiceFormState = {
	category_id: 0,
	code: "",
	cogs: "",
	price: "",
	name: "",
	description: "",
	is_active: true,
};

interface ServiceFormProps {
	defaultValues?: ServiceFormState;
	handleOnSubmit: (values: ServiceFormState) => Promise<void> | void;
	isEditing: boolean;
	onReset: () => void;
}

export function ServiceForm({
	defaultValues,
	handleOnSubmit,
	isEditing,
	onReset,
}: ServiceFormProps) {
	const form = useForm({
		resolver: zodResolver(serviceFormResolverSchema),
		defaultValues: defaultValues ?? defaultForm,
	});
	const isSubmitting = form.formState.isSubmitting;

	return (
		<form onSubmit={form.handleSubmit(handleOnSubmit)}>
			<FieldGroup>
				<Controller
					control={form.control}
					name="category_id"
					render={({ field, fieldState }) => (
						<CategoryAutocomplete
							disabled={isSubmitting}
							error={fieldState.error}
							onValueChange={(value) => field.onChange(Number(value))}
							required
							value={field.value ? String(field.value) : ""}
						/>
					)}
				/>

				<Controller
					control={form.control}
					name="code"
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="service-code" asterisk>
								Code
							</FieldLabel>
							<Input
								{...field}
								aria-invalid={fieldState.invalid}
								className="h-10"
								disabled={isSubmitting}
								id="service-code"
								placeholder="e.g. SVC-001"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					control={form.control}
					name="name"
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="service-name" asterisk>
								Name
							</FieldLabel>
							<Input
								{...field}
								aria-invalid={fieldState.invalid}
								className="h-10"
								disabled={isSubmitting}
								id="service-name"
								placeholder="e.g. Dry Clean Premium"
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					control={form.control}
					name="description"
					render={({ field, fieldState }) => (
						<Field className="md:col-span-2" data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="service-description">Description</FieldLabel>
							<Input
								{...field}
								aria-invalid={fieldState.invalid}
								className="h-10"
								disabled={isSubmitting}
								id="service-description"
								placeholder="e.g. 24-hour turnaround"
								value={field.value ?? ""}
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					control={form.control}
					name="cogs"
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="service-cogs" asterisk>
								COGS
							</FieldLabel>
							<CurrencyInput
								disabled={isSubmitting}
								id="service-cogs"
								onValueChange={field.onChange}
								placeholder="Rp0"
								required
								value={field.value}
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					control={form.control}
					name="price"
					render={({ field, fieldState }) => (
						<Field data-invalid={fieldState.invalid}>
							<FieldLabel htmlFor="service-price" asterisk>
								Price
							</FieldLabel>
							<CurrencyInput
								disabled={isSubmitting}
								id="service-price"
								onValueChange={field.onChange}
								placeholder="Rp0"
								required
								value={field.value}
							/>
							<FieldError errors={[fieldState.error]} />
						</Field>
					)}
				/>

				<Controller
					control={form.control}
					name="is_active"
					render={({ field }) => (
						<Field className="flex-row items-center justify-between md:col-span-2">
							<FieldLabel htmlFor="service-active">Active</FieldLabel>
							<Switch
								checked={field.value}
								disabled={isSubmitting}
								id="service-active"
								onCheckedChange={(checked) => field.onChange(!!checked)}
							/>
						</Field>
					)}
				/>

				<div className="flex flex-wrap gap-2 md:col-span-2 md:justify-end">
					{isEditing ? (
						<Button
							disabled={isSubmitting}
							onClick={onReset}
							type="button"
							variant="outline"
						>
							Cancel edit
						</Button>
					) : null}
					<Button
						icon={<PlusIcon className="size-4" weight="duotone" />}
						loading={isSubmitting}
						type="submit"
					>
						{isEditing ? "Update Service" : "Create Service"}
					</Button>
				</div>
			</FieldGroup>
		</form>
	);
}
