// packages/web/src/modules/payments/PaymentMethodForm.vue
<script setup lang="ts">
import { POSTPaymentMethodSchema } from '@fresclean/api/schema'
import { type FormOptions, useForm } from 'vee-validate'
import type z from 'zod'
import { Button } from '@/shared/components/ui/button'
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/shared/components/ui/form'
import { Input } from '@/shared/components/ui/input'
import { Switch } from '@/shared/components/ui/switch'

type ServiceForm = z.input<typeof POSTPaymentMethodSchema>
type ServiceFormProps = FormOptions<ServiceForm>
const props = defineProps<ServiceFormProps>()
const emit = defineEmits<{
  submit: [data: z.infer<typeof POSTPaymentMethodSchema>]
}>()

const { handleSubmit, isSubmitting } = useForm({
  ...props,
  validationSchema: POSTPaymentMethodSchema,
})

const onSubmit = handleSubmit((data) => emit('submit', data))
</script>

<template>
  <form @submit="onSubmit" class="flex flex-col gap-y-3">
    <FormField v-slot="{ componentField }" name="code">
      <FormItem>
        <FormLabel asterisk> Code </FormLabel>
        <FormControl>
          <Input placeholder="Code" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ componentField }" name="name">
      <FormItem>
        <FormLabel asterisk> Payment Method </FormLabel>
        <FormControl>
          <Input placeholder="Payment method" v-bind="componentField" />
        </FormControl>
        <FormMessage />
      </FormItem>
    </FormField>

    <FormField v-slot="{ value, handleChange }" name="is_active">
      <FormItem class="flex flex-row items-center justify-between rounded-lg border p-4">
        <div class="space-y-0.5">
          <FormLabel class="text-base"> Activation Status </FormLabel>
        </div>
        <FormControl>
          <Switch :model-value="value" @update:model-value="handleChange" />
        </FormControl>
      </FormItem>
    </FormField>

    <Button :loading="isSubmitting" size="lg" type="submit" class="w-full mt-3"> Submit </Button>
  </form>
</template>

// apps/web/src/features/payment-methods/components/payment-method-form.tsx
import { POSTPaymentMethodSchema } from "@fresclean/api/schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { PlusIcon } from "@phosphor-icons/react";
import { Controller, useForm } from "react-hook-form";
import type { z } from "zod";
import { Button } from "@/components/ui/button";
import {
	Field,
	FieldContent,
	FieldDescription,
	FieldError,
	FieldLabel,
	FieldTitle,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";

export type PaymentMethodFormState = z.infer<typeof POSTPaymentMethodSchema>;

const defaultForm: PaymentMethodFormState = {
	name: "",
	code: "",
	is_active: true,
};

type PaymentMethodFormProps = {
	defaultValues?: PaymentMethodFormState;
	handleOnSubmit: (values: PaymentMethodFormState) => Promise<void> | void;
	isEditing: boolean;
	onReset: () => void;
};

export function PaymentMethodForm({
	defaultValues,
	handleOnSubmit,
	isEditing,
	onReset,
}: PaymentMethodFormProps) {
	const form = useForm({
		resolver: zodResolver(POSTPaymentMethodSchema),
		defaultValues: defaultValues ?? defaultForm,
	});
	const isSubmitting = form.formState.isSubmitting;

	return (
		<form
			className="grid gap-4 p-4 md:grid-cols-2"
			onSubmit={form.handleSubmit(handleOnSubmit)}
		>
			<Controller
				name="name"
				control={form.control}
				render={({ field, fieldState }) => (
					<Field data-invalid={fieldState.invalid}>
						<FieldLabel htmlFor="payment-method-name" asterisk>
							Name
						</FieldLabel>
						<Input
							{...field}
							id="payment-method-name"
							placeholder="e.g. Cash"
							aria-invalid={fieldState.invalid}
							disabled={isSubmitting}
							className="h-10"
						/>
						<FieldError errors={[fieldState.error]} />
					</Field>
				)}
			/>

			<Controller
				name="code"
				control={form.control}
				render={({ field, fieldState }) => (
					<Field data-invalid={fieldState.invalid}>
						<FieldLabel htmlFor="payment-method-code" asterisk>
							Code
						</FieldLabel>
						<Input
							{...field}
							id="payment-method-code"
							placeholder="e.g. CASH"
							aria-invalid={fieldState.invalid}
							disabled={isSubmitting}
							className="h-10"
						/>
						<FieldError errors={[fieldState.error]} />
					</Field>
				)}
			/>

			<Controller
				name="is_active"
				control={form.control}
				render={({ field }) => (
					<FieldLabel htmlFor="payment-method-active" className="md:col-span-2">
						<Field orientation="horizontal">
							<FieldContent>
								<FieldTitle>Active</FieldTitle>
								<FieldDescription>
									Active payment methods can be used at checkout.
								</FieldDescription>
							</FieldContent>
							<Switch
								id="payment-method-active"
								checked={field.value}
								onCheckedChange={(checked) => field.onChange(!!checked)}
								disabled={isSubmitting}
							/>
						</Field>
					</FieldLabel>
				)}
			/>

			<div className="flex flex-wrap gap-2 md:col-span-2 md:justify-end">
				{isEditing ? (
					<Button
						type="button"
						variant="outline"
						onClick={onReset}
						disabled={isSubmitting}
					>
						Cancel edit
					</Button>
				) : null}
				<Button
					type="submit"
					loading={isSubmitting}
					icon={<PlusIcon className="size-4" />}
				>
					{isEditing ? "Update Method" : "Create Method"}
				</Button>
			</div>
		</form>
	);
}
