// packages/web/src/shared/components/ui/dialog/GlobalDialog.vue
<script setup lang="ts">
import { useDialogStore } from '@/core/stores/dialog-store'
import Dialog from './Dialog.vue'
import DialogContent from './DialogContent.vue'
import DialogHeader from './DialogHeader.vue'
import DialogTitle from './DialogTitle.vue'
import DialogDescription from './DialogDescription.vue'
import { storeToRefs } from 'pinia'
import { cn } from '@/shared/utils'

const dialogStore = useDialogStore()
const { dialogState } = storeToRefs(dialogStore)

// only handle close as open state will be handled by the store hooks
function handleOpenChange(open: boolean) {
  if (!open) {
    dialogStore.closeDialog()
  }
}
</script>

<template>
  <Dialog :open="dialogState.open" @update:open="handleOpenChange">
    <DialogContent class="max-h-[90dvh] overflow-y-auto">
      <DialogHeader v-if="dialogState.title || dialogState.description">
        <DialogTitle>
          {{ dialogState.title }}
        </DialogTitle>
        <DialogDescription
          :class="
            cn({
              'sr-only': !dialogState.description,
            })
          "
        >
          {{ dialogState.description || dialogState.title }}
        </DialogDescription>
      </DialogHeader>

      <component :is="dialogState.content" />
    </DialogContent>
  </Dialog>
</template>

// packages/web/src/components/ui/global-dialog.tsx
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { useDialog } from "@/stores/dialog-store";

export function GlobalDialog() {
	const { open, title, description, content, footer } = useDialog(
		(state) => state.dialogState,
	);
	const closeDialog = useDialog((state) => state.closeDialog);

	return (
		<Dialog
			open={open}
			onOpenChange={(nextOpen) => {
				if (!nextOpen) {
					closeDialog();
				}
			}}
		>
			<DialogContent>
				{title || description ? (
					<DialogHeader>
						{title ? <DialogTitle>{title}</DialogTitle> : null}
						<DialogDescription
							className={cn({
								"sr-only": !description,
							})}
						>
							{description || title}
						</DialogDescription>
					</DialogHeader>
				) : null}
				{content ? <div className="py-4">{content}</div> : null}
				{footer ? <DialogFooter>{footer}</DialogFooter> : null}
			</DialogContent>
		</Dialog>
	);
}
