// packages/web/src/components/ui/label.tsx
/** biome-ignore-all lint/a11y/noLabelWithoutControl: <reusable component> */
import type * as React from "react";

import { cn } from "@/lib/utils";

function Label({ className, ...props }: React.ComponentProps<"label">) {
	return (
		<label
			data-slot="label"
			className={cn(
				"flex items-center gap-2 text-xs leading-none select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
				className,
			)}
			{...props}
		/>
	);
}

export { Label };

// packages/web/src/shared/components/ui/label/Label.vue
<script setup lang="ts">
import type { LabelProps } from 'reka-ui'
import type { HTMLAttributes } from 'vue'
import { Label } from 'reka-ui'
import { cn } from '@/shared/utils'

const { class: className, ...props } = defineProps<
  LabelProps & { class?: HTMLAttributes['class'] }
>()
</script>

<template>
  <Label
    data-slot="label"
    v-bind="props"
    :class="
      cn(
        'inline-flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        className,
      )
    "
  >
    <slot />
  </Label>
</template>
